# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: https://github.com/psf/black
  rev: "20.8b1"
  hooks:
  - id: black

- repo: https://github.com/PyCQA/isort
  rev: "5.7.0"
  hooks:
  - id: isort

- repo: https://gitlab.com/PyCQA/flake8
  rev: "3.8.4"
  hooks:
  - id: flake8

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: "v0.812"
  hooks:
  - id: mypy

- repo: https://github.com/asottile/pyupgrade
  rev: "v2.10.0"
  hooks:
  - id: pyupgrade

- repo: https://github.com/PyCQA/doc8
  rev: "0.8.1"
  hooks:
  - id: doc8
