[tool.poetry]
name = "pypitoken"
version = "0.0.0"
description = "Manipulate PyPI API tokens"
authors = ["Joachim Jablon <ewjoachim@gmail.com>"]
classifiers = [
    "Topic :: Security",
    "Topic :: System :: Archiving :: Packaging"
]

[tool.poetry.dependencies]
python = "^3.6.1"
pymacaroons = "^0.13.0"
jsonschema = "*"
dataclasses = { version = "*", python = "~3.6" }


[tool.poetry.dev-dependencies]
pre-commit = "^2.10.1"
pytest = "^5.2"
pytest-cov = "^2.11.1"
Sphinx = "^3.5.1"
sphinx-material = "^0.0.32"
sphinx-github-changelog = "^1.0.2"
sphinx-autodoc-typehints = "^1.11.1"
dunamai = "^1.5.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
