[tool.poetry]
name = "pypitoken"
version = "0.1.0"
description = ""
authors = ["Joachim Jablon <ewjoachim@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6.1"
pymacaroons = "^0.13.0"
jsonschema = "^3.2.0"

[tool.poetry.dev-dependencies]
pre-commit = "^2.10.1"
pytest = "^5.2"
black = "^20.8b1"
isort = "^5.7.0"
flake8 = "^3.8.4"
mypy = "^0.812"
pyupgrade = "^2.10.0"
pytest-cov = "^2.11.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
