[tool.poetry]
name = "pypitoken"
version = "0.0.0"
description = "Manipulate PyPI API tokens"
license = "MIT"
authors = ["Joachim Jablon <ewjoachim@gmail.com>"]
classifiers = [
    "Topic :: Security",
    "Topic :: System :: Archiving :: Packaging"
]
readme = "README.rst"
homepage = "https://pypitoken.readthedocs.io/en/latest/"
repository = "https://github.com/ewjoachim/pypitoken"
documentation = "https://pypitoken.readthedocs.io/en/latest/"
keywords = ["pypi", "api", "token", "security", "packaging"]

[tool.poetry.dependencies]
python = "^3.6"
pymacaroons = "^0.13.0"
jsonschema = "*"
dataclasses = { version = "*", python = "~3.6" }


[tool.poetry.dev-dependencies]
pytest = "^6.2"
pytest-cov = "^3.0.0"
Sphinx = "<4"
sphinx-material = "^0.0.35"
sphinx-github-changelog = "^1.0.2"
sphinx-autodoc-typehints = "^1.11.1"
dunamai = "^1.7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
