name: CI

on:
  pull_request:
  push:
    branches:
      - 'master'
    tags:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - tox-env: lint
            python-version: 3.x
          - python-version: 3.6
            tox-env: py36-tests
          - python-version: 3.7
            tox-env: py37-tests
          - python-version: 3.8
            tox-env: py38-tests
          - python-version: 3.9
            tox-env: py39-tests

    name: ${{ matrix.tox-env }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: set PY
        run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: Cache poetry
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: poetry-${{ env.PY }}-${{ hashFiles('poetry.lock') }}

      - name: Cache pre-commit
        uses: actions/cache@v1
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ env.PY }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Install dependencies
        run: |
          set -xeu
          python -VV
          pip install tox coverage

      - name: Run tox env ${{ matrix.tox-env }}
        run: tox -e ${{ matrix.tox-env }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        if: ${{ contains(matrix.tox-env, 'tests') }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
