name: CI

on:
  pull_request:
  push:
    branches:
      - 'master'
    tags:
      - '*'

jobs:
  build:

    strategy:
      matrix:
        include:
          - python_version: "3.7"
            script: tests
          - python_version: "3.8"
            script: tests
          - python_version: "3.9"
            script: tests
          - python_version: "3.10"
            script: tests

    name: "py${{ matrix.python_version }} / ${{ matrix.script }}"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}

      - name: Pip, Pre-commit & Poetry caches
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/
          key: ${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('poetry.lock') }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Install Poetry
        run: pip install poetry

      - name: Install Dev dependencies
        run: poetry install

      - name: Run ${{ matrix.script }}
        run: scripts/${{ matrix.script }}
        env:
          PYTEST_ADDOPTS: "--cov-report=xml"

      # - name: Display coverage
      #   uses: ewjoachim/coverage-comment-action@v1
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  report-status:
    name: success
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Report success
        run: echo 'Success !'
