name: CI

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '*'

env:
  UV_FROZEN: "true"

permissions:
  contents: read

jobs:
  tests:
    strategy:
      matrix:
        python_version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    name: "py${{ matrix.python_version }}"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up UV
        id: setup-uv
        uses: astral-sh/setup-uv@1c15d185f03657a1644ed2684496fb7c6ed59815
        with:
          python-version: ${{ matrix.python_version }}
          enable-cache: false

      - name: Run tests
        run: uv run pytest
        env:
          GITHUB_TOKEN: ${{ github.token }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          python-version: "3.14"
          enable-cache: false

      - name: Install dependencies
        run: uv sync --all-groups

      - name: Run prek
        run: uv run --group dev prek run --all-files

  publish:
    name: Publish package to PyPI
    if: github.event_name == 'push' && github.ref_type == 'tag'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    needs:
      - tests
      - lint
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Build wheel & sdist
        run: pipx run uv build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2
