name: CI

on:
  pull_request:
  push:
    branches:
      - 'master'
    tags:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - tox-env: lint
            python-version: 3.x
          - python-version: 3.6
            tox-env: py36-tests
          - python-version: 3.7
            tox-env: py37-tests
          - python-version: 3.8
            tox-env: py38-tests
          - python-version: 3.9
            tox-env: py39-tests

    name: ${{ matrix.tox-env }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pypoetry/virtualenvs
            ~/.cache/pre-commit
          key: ${{ matrix.tox-env }}-${{ hashFiles('poetry.lock') }}

      - name: Install dependencies
        run: |
          set -xeu
          python -VV
          pip install tox coverage

      - name: Run tox env ${{ matrix.tox-env }}
        run: tox -e ${{ matrix.tox-env }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        if: ${{ contains(matrix.tox-env, 'tests') }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

  report-status:
    name: success
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Report success
        run: echo 'Success !'
