name: Deploy

on:
  push:
    tags:
      - '*'
  release:
    types:
      - published

jobs:
  deploy:
    name: Publish package to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Wait for tests to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-ci
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: success
      - name: Exit if CI did not succeed
        if: steps.wait-for-ci.outputs.conclusion != 'success'
        run: exit 1
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install build
      - name: Build the wheel
        run: python -m build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
